# Generated by Django 3.1.2 on 2020-12-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0017_remove_turingmachinedb_excel_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turingmachinedb',
            name='aws_file_key',
        ),
        migrations.RemoveField(
            model_name='turingmachinedb',
            name='aws_file_path',
        ),
    ]
